$axure.loadCurrentPage({
  "url":"judge_text.html",
  "generationDate":new Date(1396428148443.81),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ec61b780c89a4588a2f939cf64f76fa6",
    "type":"Axure:Page",
    "name":"Judge text",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setWidgetSize",
                "description":"Set Size of winner confirmation popup to 0 x 0",
                "objectsToResize":[{
                    "objectPath":["467b03a2529348a7a49b7ecf8fe336df"],
                    "sizeInfo":{
                      "width":{
                        "exprType":"stringLiteral",
                        "value":"0",
                        "stos":[]},
                      "height":{
                        "exprType":"stringLiteral",
                        "value":"0",
                        "stos":[]},
                      "easing":"none",
                      "duration":1000}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"66e34840702941d0b6c6e5b75386019a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":446,
              "y":110},
            "size":{
              "width":335,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3d3455028a94212aeb12b937f044eb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":446,
                  "y":110},
                "size":{
                  "width":335,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90049410b8754ac1aee46f739746dacd",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":190},
            "size":{
              "width":1180,
              "height":150}},
          "adaptiveStyles":{
}},
{
          "id":"e34ed8bbeddb48d0ab956f5bddda07a0",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"14818115d01f47f99a32087a167b2c37"},
{
          "id":"d990ec6f7ce14ce3b5a0df19b7764813",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":390},
            "size":{
              "width":560,
              "height":261}},
          "adaptiveStyles":{
}},
{
          "id":"df1c339efbe544a2b3dcf40d7391f10b",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":390},
            "size":{
              "width":560,
              "height":261}},
          "adaptiveStyles":{
}},
{
          "id":"948e94c1fe164040bfe13a0707d4796a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":-10,
              "y":1980},
            "size":{
              "width":1200,
              "height":100},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c69d61749d5a4cc9907740bb19baeb8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":-10,
                  "y":1980},
                "size":{
                  "width":1200,
                  "height":100},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/judge_text/u14.png"}},
{
          "id":"467b03a2529348a7a49b7ecf8fe336df",
          "label":"winner confirmation popup",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":1286,
              "height":1580}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"4827071e13534095a0f25ad42c9bf152",
              "label":"text F22 won",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"87b76a48676d40f9a27de7bcb9f3521d",
                  "label":"",
                  "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "masterId":"f4885c44fb0d46de8c5935239991d560"},
{
                  "id":"6b6e6a3de4aa4c748a87ba14230cebe3",
                  "label":"",
                  "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":390,
                      "y":118},
                    "size":{
                      "width":457,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b80416f60d8e4441bfcdfffaa3927e6e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":390,
                          "y":118},
                        "size":{
                          "width":457,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"de95c5e188bc4f779d829f5396d37918",
                  "label":"",
                  "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":760,
                      "y":278},
                    "size":{
                      "width":100,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"168aed17dd7147c99c40426d5558a132",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":760,
                          "y":278},
                        "size":{
                          "width":100,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Judge text in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"judge_text.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/frontpage/u3.png"}},
{
                  "id":"ada44610b1c44d9598bf06772c7d9035",
                  "label":"",
                  "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":390,
                      "y":278},
                    "size":{
                      "width":100,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0bad558ad97d4b92a1d8475f0e61bfd6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":390,
                          "y":278},
                        "size":{
                          "width":100,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Judge text in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"judge_text.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/frontpage/u3.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"26e40f1c5ddb4ed5a4bddf60d45b9504",
              "label":"text Z4 won",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"85d02ec997f149758e3c2bff8ddfcdaf",
                  "label":"",
                  "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "masterId":"f4885c44fb0d46de8c5935239991d560"},
{
                  "id":"4dbc1ece58334ac88ce6df03783b8e41",
                  "label":"",
                  "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":319,
                      "y":120},
                    "size":{
                      "width":442,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"884ff7173efd4dedafbb8d406b47c78c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":319,
                          "y":120},
                        "size":{
                          "width":442,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"54318fff7adf432584d8216f783371bd",
                  "label":"",
                  "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":664,
                      "y":278},
                    "size":{
                      "width":100,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4564e15f40ee41749ea056fbe984b4b2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":664,
                          "y":278},
                        "size":{
                          "width":100,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Judge text in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"judge_text.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/frontpage/u3.png"}},
{
                  "id":"dfdb8b942b164d3188171e7b0e112603",
                  "label":"",
                  "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":319,
                      "y":278},
                    "size":{
                      "width":100,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"11f316e9a4fe4470bb06354fcd5fec34",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":319,
                          "y":278},
                        "size":{
                          "width":100,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Judge text in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"judge_text.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/frontpage/u3.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"0bd6980863fd4bb6909bfcc22f7b10e9",
          "label":"winner A button",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":715},
            "size":{
              "width":140,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0733753b0184d0ca28fcf98a2421303",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":329,
                  "y":715},
                "size":{
                  "width":140,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"scrollToWidget",
                      "description":"Scroll to Assessor - Navigation logged in/(Image) (y only)",
                      "objectPath":["e34ed8bbeddb48d0ab956f5bddda07a0",
"21e93a6843644148a85b03371aa66f65"],
                      "options":{
                        "direction":"vertical"}},
{
                      "action":"setWidgetSize",
                      "description":"Set Size of winner confirmation popup to 1250 x 1600",
                      "objectsToResize":[{
                          "objectPath":["467b03a2529348a7a49b7ecf8fe336df"],
                          "sizeInfo":{
                            "width":{
                              "exprType":"stringLiteral",
                              "value":"1250",
                              "stos":[]},
                            "height":{
                              "exprType":"stringLiteral",
                              "value":"1600",
                              "stos":[]},
                            "easing":"none",
                            "duration":1000}}]},
{
                      "action":"setPanelState",
                      "description":"Set winner confirmation popup to text F22 won",
                      "panelsToStates":[{
                          "panelPath":["467b03a2529348a7a49b7ecf8fe336df"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/judge_text/winner_a_button_u39.png"}},
{
          "id":"c656ce5fa82a4edfb110832a41a3eb58",
          "label":"winner B button",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":969,
              "y":715},
            "size":{
              "width":140,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7f4250987bb4f66931fc64ba302f940",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":969,
                  "y":715},
                "size":{
                  "width":140,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"scrollToWidget",
                      "description":"Scroll to Assessor - Navigation logged in/(Image) (y only)",
                      "objectPath":["e34ed8bbeddb48d0ab956f5bddda07a0",
"21e93a6843644148a85b03371aa66f65"],
                      "options":{
                        "direction":"vertical"}},
{
                      "action":"setWidgetSize",
                      "description":"Set Size of winner confirmation popup to 1250 x 1600",
                      "objectsToResize":[{
                          "objectPath":["467b03a2529348a7a49b7ecf8fe336df"],
                          "sizeInfo":{
                            "width":{
                              "exprType":"stringLiteral",
                              "value":"1250",
                              "stos":[]},
                            "height":{
                              "exprType":"stringLiteral",
                              "value":"1600",
                              "stos":[]},
                            "easing":"none",
                            "duration":1000}}]},
{
                      "action":"setPanelState",
                      "description":"Set winner confirmation popup to text Z4 won",
                      "panelsToStates":[{
                          "panelPath":["467b03a2529348a7a49b7ecf8fe336df"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/judge_text/winner_a_button_u39.png"}},
{
          "id":"4385d92aa1a945bf9951e171123e5f74",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":680}},
          "adaptiveStyles":{
},
          "masterId":"cd8ed5398a604449bc3e5bd0e00b50ea"},
{
          "id":"98308f0a84174a47a760ba1fb4b33a3a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":727,
              "y":680}},
          "adaptiveStyles":{
},
          "masterId":"cd8ed5398a604449bc3e5bd0e00b50ea"},
{
          "id":"ac21e6701d144b6d81a0d38ffec35db2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":803},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b93a925d53f04dc7b163516ede556cea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":803},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5255a26171ab4ff39e6202ff74b3f239",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":867,
              "y":800},
            "size":{
              "width":100,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0dd2460f63844baafd6dc0b5e68e3d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":867,
                  "y":800},
                "size":{
                  "width":100,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1bf9149b35f451183faf122ed0dfc9f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":846},
            "size":{
              "width":561,
              "height":810},
            "borderWidth":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e35bc25679b4256b7e4cc010bf2517f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":846},
                "size":{
                  "width":561,
                  "height":810},
                "borderWidth":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/judge_text/u65.png"}},
{
          "id":"7b9aafee082c404b813b66ba4479eaa6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":629,
              "y":846},
            "size":{
              "width":560,
              "height":810},
            "borderWidth":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eba95009beac42dcae540d5ab8c87d69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":629,
                  "y":846},
                "size":{
                  "width":560,
                  "height":810},
                "borderWidth":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/judge_text/u67.png"}},
{
          "id":"d4dddbc9265f4764aef8d76a8bd32055",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":331,
              "y":808},
            "size":{
              "width":17,
              "height":17},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0883b941f70b4df1bc5a3e73de531da6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":331,
                  "y":808},
                "size":{
                  "width":17,
                  "height":17},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/judge_text/u69.png"}},
{
          "id":"4cf88d0b30f946d4bd88c0151d599d57",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":971,
              "y":806},
            "size":{
              "width":17,
              "height":17},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3915b4763724c1f8666928c93651ded",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":971,
                  "y":806},
                "size":{
                  "width":17,
                  "height":17},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/judge_text/u69.png"}},
{
          "id":"cb0b9f7296d94ca78e7ab27a9cba380e",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":1685},
            "size":{
              "width":560,
              "height":260}},
          "adaptiveStyles":{
}},
{
          "id":"41b164983be84fc4846aedc0f73981c2",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1685},
            "size":{
              "width":560,
              "height":260}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "14818115d01f47f99a32087a167b2c37":{
      "packageId":"14818115d01f47f99a32087a167b2c37",
      "type":"Axure:Master",
      "name":"Assessor - Navigation logged in",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"21e93a6843644148a85b03371aa66f65",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":7},
              "size":{
                "width":120,
                "height":76}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"288080d3ea61437a8ab3dcd742a527a3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":7},
                  "size":{
                    "width":120,
                    "height":76}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/frontpage/u1.png"}},
{
            "id":"d7cce145214f41bfbc63f094a4be971f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":830,
                "y":30},
              "size":{
                "width":100,
                "height":30},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f42e483fc3c34f72a29f0d79f2b73812",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":830,
                    "y":30},
                  "size":{
                    "width":100,
                    "height":30},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Judge text in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"judge_text.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/frontpage/u3.png"}},
{
            "id":"1c05e89a69dc42fabb5624cf6fe99da3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":960,
                "y":30},
              "size":{
                "width":100,
                "height":30},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"58b355072b67418aa9d36e56eb847646",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":960,
                    "y":30},
                  "size":{
                    "width":100,
                    "height":30},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Account in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"account.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/frontpage/u3.png"}},
{
            "id":"5a869bed0e234a1a9a2fd89d3d07abc5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":1090,
                "y":30},
              "size":{
                "width":100,
                "height":30},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59bde9dac5084b7ca662286523ad3b20",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1090,
                    "y":30},
                  "size":{
                    "width":100,
                    "height":30},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Frontpage in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"frontpage.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/frontpage/u3.png"}}]}},
    "f4885c44fb0d46de8c5935239991d560":{
      "packageId":"f4885c44fb0d46de8c5935239991d560",
      "type":"Axure:Master",
      "name":"Asessor - Judgement popup background",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f2ef4542332e41989a2c360a86a6df2b",
            "label":"Rectangle",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "opacity":"0.8",
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":-350,
                "y":-270},
              "size":{
                "width":1550,
                "height":1570},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF999999}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3be3eb3150a54a60a65d70d38981a7bf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "opacity":"0.8",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":-350,
                    "y":-270},
                  "size":{
                    "width":1550,
                    "height":1570},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF999999}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/judge_text/rectangle_u18.png",
              "normal~":"images/judge_text/rectangle_u18.png"}},
{
            "id":"81ea4546eed64b6abfea7f86e5337273",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "opacity":"0.8",
              "fill":{
                "fillType":"solid",
                "color":0xFF0099FF},
              "location":{
                "x":230,
                "y":50},
              "size":{
                "width":740,
                "height":340},
              "cornerRadiusTopLeft":"10"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a1133b112281405885f764ba66ccc361",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "opacity":"0.8",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF},
                  "location":{
                    "x":230,
                    "y":50},
                  "size":{
                    "width":740,
                    "height":340},
                  "cornerRadiusTopLeft":"10"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/judge_text/u20.png",
              "normal~":"images/judge_text/u20.png"}}]}},
    "cd8ed5398a604449bc3e5bd0e00b50ea":{
      "packageId":"cd8ed5398a604449bc3e5bd0e00b50ea",
      "type":"Axure:Master",
      "name":"Assessor - succeed/fail widget",
      "notes":{
        "Default":"<p><span>Check on submit if not blanc</span></p>"},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"b5506ea8a5cc4f2a8dc968f89a106fd8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "horizontalAlignment":"left",
              "verticalAlignment":"top",
              "location":{
                "x":10,
                "y":0},
              "size":{
                "width":180,
                "height":100},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"30e6787de25f44dea73ba6fe1bd50c0c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"left",
                  "verticalAlignment":"top",
                  "location":{
                    "x":10,
                    "y":0},
                  "size":{
                    "width":180,
                    "height":100},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/judge_text/u44.png",
              "normal~":"images/judge_text/u44.png"}},
{
            "id":"a44e5786f65d47e18706ddcc9b34ef1c",
            "label":"",
            "type":"radioButton",
            "styleType":"radioButton",
            "visible":true,
            "style":{
              "location":{
                "x":70,
                "y":25},
              "size":{
                "width":100,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b62e39f2154a46e59f8300fc81d47dd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":70,
                    "y":25},
                  "size":{
                    "width":100,
                    "height":15}},
                "adaptiveStyles":{
}}]},
{
            "id":"2f4622d1335a4523aa6c3020b28c84e9",
            "label":"",
            "type":"radioButton",
            "styleType":"radioButton",
            "visible":true,
            "style":{
              "location":{
                "x":70,
                "y":50},
              "size":{
                "width":100,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"158eadccc266435bbc662f553c6b3c47",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":70,
                    "y":50},
                  "size":{
                    "width":100,
                    "height":15}},
                "adaptiveStyles":{
}}]},
{
            "id":"3b6242d3da9a4a9693b23080d3f87cc6",
            "label":"",
            "type":"radioButton",
            "styleType":"radioButton",
            "visible":true,
            "style":{
              "location":{
                "x":70,
                "y":75},
              "size":{
                "width":100,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4ca62baf7aa2418f8e4203672cf661b7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":70,
                    "y":75},
                  "size":{
                    "width":100,
                    "height":15}},
                "adaptiveStyles":{
}}]}]}}},
  "objectPaths":{
    "66e34840702941d0b6c6e5b75386019a":{
      "scriptId":"u0"},
    "e3d3455028a94212aeb12b937f044eb5":{
      "scriptId":"u1"},
    "90049410b8754ac1aee46f739746dacd":{
      "scriptId":"u2"},
    "e34ed8bbeddb48d0ab956f5bddda07a0":{
      "scriptId":"u3",
      "21e93a6843644148a85b03371aa66f65":{
        "scriptId":"u4"},
      "288080d3ea61437a8ab3dcd742a527a3":{
        "scriptId":"u5"},
      "d7cce145214f41bfbc63f094a4be971f":{
        "scriptId":"u6"},
      "f42e483fc3c34f72a29f0d79f2b73812":{
        "scriptId":"u7"},
      "1c05e89a69dc42fabb5624cf6fe99da3":{
        "scriptId":"u8"},
      "58b355072b67418aa9d36e56eb847646":{
        "scriptId":"u9"},
      "5a869bed0e234a1a9a2fd89d3d07abc5":{
        "scriptId":"u10"},
      "59bde9dac5084b7ca662286523ad3b20":{
        "scriptId":"u11"}},
    "d990ec6f7ce14ce3b5a0df19b7764813":{
      "scriptId":"u12"},
    "df1c339efbe544a2b3dcf40d7391f10b":{
      "scriptId":"u13"},
    "948e94c1fe164040bfe13a0707d4796a":{
      "scriptId":"u14"},
    "c69d61749d5a4cc9907740bb19baeb8a":{
      "scriptId":"u15"},
    "467b03a2529348a7a49b7ecf8fe336df":{
      "scriptId":"u16"},
    "87b76a48676d40f9a27de7bcb9f3521d":{
      "scriptId":"u17",
      "f2ef4542332e41989a2c360a86a6df2b":{
        "scriptId":"u18"},
      "3be3eb3150a54a60a65d70d38981a7bf":{
        "scriptId":"u19"},
      "81ea4546eed64b6abfea7f86e5337273":{
        "scriptId":"u20"},
      "a1133b112281405885f764ba66ccc361":{
        "scriptId":"u21"}},
    "6b6e6a3de4aa4c748a87ba14230cebe3":{
      "scriptId":"u22"},
    "b80416f60d8e4441bfcdfffaa3927e6e":{
      "scriptId":"u23"},
    "de95c5e188bc4f779d829f5396d37918":{
      "scriptId":"u24"},
    "168aed17dd7147c99c40426d5558a132":{
      "scriptId":"u25"},
    "ada44610b1c44d9598bf06772c7d9035":{
      "scriptId":"u26"},
    "0bad558ad97d4b92a1d8475f0e61bfd6":{
      "scriptId":"u27"},
    "85d02ec997f149758e3c2bff8ddfcdaf":{
      "scriptId":"u28",
      "f2ef4542332e41989a2c360a86a6df2b":{
        "scriptId":"u29"},
      "3be3eb3150a54a60a65d70d38981a7bf":{
        "scriptId":"u30"},
      "81ea4546eed64b6abfea7f86e5337273":{
        "scriptId":"u31"},
      "a1133b112281405885f764ba66ccc361":{
        "scriptId":"u32"}},
    "4dbc1ece58334ac88ce6df03783b8e41":{
      "scriptId":"u33"},
    "884ff7173efd4dedafbb8d406b47c78c":{
      "scriptId":"u34"},
    "54318fff7adf432584d8216f783371bd":{
      "scriptId":"u35"},
    "4564e15f40ee41749ea056fbe984b4b2":{
      "scriptId":"u36"},
    "dfdb8b942b164d3188171e7b0e112603":{
      "scriptId":"u37"},
    "11f316e9a4fe4470bb06354fcd5fec34":{
      "scriptId":"u38"},
    "0bd6980863fd4bb6909bfcc22f7b10e9":{
      "scriptId":"u39"},
    "c0733753b0184d0ca28fcf98a2421303":{
      "scriptId":"u40"},
    "c656ce5fa82a4edfb110832a41a3eb58":{
      "scriptId":"u41"},
    "e7f4250987bb4f66931fc64ba302f940":{
      "scriptId":"u42"},
    "4385d92aa1a945bf9951e171123e5f74":{
      "scriptId":"u43",
      "b5506ea8a5cc4f2a8dc968f89a106fd8":{
        "scriptId":"u44"},
      "30e6787de25f44dea73ba6fe1bd50c0c":{
        "scriptId":"u45"},
      "a44e5786f65d47e18706ddcc9b34ef1c":{
        "scriptId":"u46"},
      "b62e39f2154a46e59f8300fc81d47dd8":{
        "scriptId":"u47"},
      "2f4622d1335a4523aa6c3020b28c84e9":{
        "scriptId":"u48"},
      "158eadccc266435bbc662f553c6b3c47":{
        "scriptId":"u49"},
      "3b6242d3da9a4a9693b23080d3f87cc6":{
        "scriptId":"u50"},
      "4ca62baf7aa2418f8e4203672cf661b7":{
        "scriptId":"u51"}},
    "98308f0a84174a47a760ba1fb4b33a3a":{
      "scriptId":"u52",
      "b5506ea8a5cc4f2a8dc968f89a106fd8":{
        "scriptId":"u53"},
      "30e6787de25f44dea73ba6fe1bd50c0c":{
        "scriptId":"u54"},
      "a44e5786f65d47e18706ddcc9b34ef1c":{
        "scriptId":"u55"},
      "b62e39f2154a46e59f8300fc81d47dd8":{
        "scriptId":"u56"},
      "2f4622d1335a4523aa6c3020b28c84e9":{
        "scriptId":"u57"},
      "158eadccc266435bbc662f553c6b3c47":{
        "scriptId":"u58"},
      "3b6242d3da9a4a9693b23080d3f87cc6":{
        "scriptId":"u59"},
      "4ca62baf7aa2418f8e4203672cf661b7":{
        "scriptId":"u60"}},
    "ac21e6701d144b6d81a0d38ffec35db2":{
      "scriptId":"u61"},
    "b93a925d53f04dc7b163516ede556cea":{
      "scriptId":"u62"},
    "5255a26171ab4ff39e6202ff74b3f239":{
      "scriptId":"u63"},
    "d0dd2460f63844baafd6dc0b5e68e3d2":{
      "scriptId":"u64"},
    "a1bf9149b35f451183faf122ed0dfc9f":{
      "scriptId":"u65"},
    "7e35bc25679b4256b7e4cc010bf2517f":{
      "scriptId":"u66"},
    "7b9aafee082c404b813b66ba4479eaa6":{
      "scriptId":"u67"},
    "eba95009beac42dcae540d5ab8c87d69":{
      "scriptId":"u68"},
    "d4dddbc9265f4764aef8d76a8bd32055":{
      "scriptId":"u69"},
    "0883b941f70b4df1bc5a3e73de531da6":{
      "scriptId":"u70"},
    "4cf88d0b30f946d4bd88c0151d599d57":{
      "scriptId":"u71"},
    "e3915b4763724c1f8666928c93651ded":{
      "scriptId":"u72"},
    "cb0b9f7296d94ca78e7ab27a9cba380e":{
      "scriptId":"u73"},
    "41b164983be84fc4846aedc0f73981c2":{
      "scriptId":"u74"}}});