$axure.loadCurrentPage({
  "url":"judge_text.html",
  "generationDate":new Date(1401888979858.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ec61b780c89a4588a2f939cf64f76fa6",
    "type":"Axure:Page",
    "name":"Judge text",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setWidgetSize",
                "description":"Set Size of Panel",
                "objectsToResize":[]}]}]}},
    "diagram":{
      "objects":[{
          "id":"66e34840702941d0b6c6e5b75386019a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":446,
              "y":115},
            "size":{
              "width":335,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3d3455028a94212aeb12b937f044eb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":446,
                  "y":115},
                "size":{
                  "width":335,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90049410b8754ac1aee46f739746dacd",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":195},
            "size":{
              "width":1180,
              "height":150}},
          "adaptiveStyles":{
}},
{
          "id":"e34ed8bbeddb48d0ab956f5bddda07a0",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"14818115d01f47f99a32087a167b2c37"},
{
          "id":"948e94c1fe164040bfe13a0707d4796a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":-10,
              "y":2045},
            "size":{
              "width":1200,
              "height":100},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c69d61749d5a4cc9907740bb19baeb8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":-10,
                  "y":2045},
                "size":{
                  "width":1200,
                  "height":100},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/judge_text/u12.png"}},
{
          "id":"ac21e6701d144b6d81a0d38ffec35db2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":358},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b93a925d53f04dc7b163516ede556cea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":358},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5255a26171ab4ff39e6202ff74b3f239",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":868,
              "y":355},
            "size":{
              "width":100,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0dd2460f63844baafd6dc0b5e68e3d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":868,
                  "y":355},
                "size":{
                  "width":100,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1bf9149b35f451183faf122ed0dfc9f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":401},
            "size":{
              "width":561,
              "height":810},
            "borderWidth":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e35bc25679b4256b7e4cc010bf2517f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":401},
                "size":{
                  "width":561,
                  "height":810},
                "borderWidth":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/judge_text/u18.png"}},
{
          "id":"7b9aafee082c404b813b66ba4479eaa6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":401},
            "size":{
              "width":560,
              "height":810},
            "borderWidth":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eba95009beac42dcae540d5ab8c87d69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":401},
                "size":{
                  "width":560,
                  "height":810},
                "borderWidth":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/judge_text/u20.png"}},
{
          "id":"d4dddbc9265f4764aef8d76a8bd32055",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":332,
              "y":363},
            "size":{
              "width":17,
              "height":17},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0883b941f70b4df1bc5a3e73de531da6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":332,
                  "y":363},
                "size":{
                  "width":17,
                  "height":17},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/judge_text/u22.png"}},
{
          "id":"4cf88d0b30f946d4bd88c0151d599d57",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":972,
              "y":361},
            "size":{
              "width":17,
              "height":17},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3915b4763724c1f8666928c93651ded",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":972,
                  "y":361},
                "size":{
                  "width":17,
                  "height":17},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/judge_text/u22.png"}},
{
          "id":"cb0b9f7296d94ca78e7ab27a9cba380e",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":631,
              "y":1240},
            "size":{
              "width":560,
              "height":260}},
          "adaptiveStyles":{
},
          "annotation":{
            "Description":"Field should be collapsable and collapsed by default"}},
{
          "id":"41b164983be84fc4846aedc0f73981c2",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":1240},
            "size":{
              "width":560,
              "height":260}},
          "adaptiveStyles":{
},
          "annotation":{
            "Description":"Field should be collapsable and collapsed by default"}},
{
          "id":"b607696d51244291b0f39c58ed335861",
          "label":"Bottow panel",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1514},
            "size":{
              "width":1180,
              "height":470}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"a6b0224bfed64d588627f69627e0d984",
              "label":"Comparative fb and winner",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0e4ccd11698b4761b616f903a1cdc9a8",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"textArea",
                  "styleType":"textArea",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":39},
                    "size":{
                      "width":1180,
                      "height":260}},
                  "adaptiveStyles":{
}},
{
                  "id":"2356e11b34fa4d68abfe6782e6cbc4a2",
                  "label":"winner A button",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":329},
                    "size":{
                      "width":140,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d6e63e75dc1a4e85a7ebe2007c543331",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":220,
                          "y":329},
                        "size":{
                          "width":140,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"switch bottom panel",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Bottow panel to F22 Unique feedback and pass/fail",
                              "panelsToStates":[{
                                  "panelPath":["b607696d51244291b0f39c58ed335861"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/judge_text/winner_a_button_u30.png"}},
{
                  "id":"ca750648c46348c5a5694921251589a4",
                  "label":"winner B button",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":800,
                      "y":329},
                    "size":{
                      "width":140,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3de380b8f0a04f3e92fa68ea3ae3fcd3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":800,
                          "y":329},
                        "size":{
                          "width":140,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Bottow panel to Z4 Unique feedback and pass/fail",
                              "panelsToStates":[{
                                  "panelPath":["b607696d51244291b0f39c58ed335861"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/judge_text/winner_a_button_u30.png"}},
{
                  "id":"5d743a04e4ef4ad9925803574a1bf77c",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":174.5,
                      "y":0},
                    "size":{
                      "width":831,
                      "height":37}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6a4eed4b02ec4c498aebf4f4a36cb250",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":174.5,
                          "y":0},
                        "size":{
                          "width":831,
                          "height":37}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"ba558407cca24ac68375ec22a79ddfb4",
              "label":"F22 Unique feedback and pass/fail",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"58ab3fc4241642ad9aa6ea490d01102d",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"textArea",
                  "styleType":"textArea",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":620,
                      "y":73},
                    "size":{
                      "width":560,
                      "height":261}},
                  "adaptiveStyles":{
}},
{
                  "id":"0ee5702d438642c988d8b36d5b5ae8cf",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"textArea",
                  "styleType":"textArea",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":73},
                    "size":{
                      "width":560,
                      "height":261}},
                  "adaptiveStyles":{
}},
{
                  "id":"ece8781e26ec4ecc8300d253ba5a6823",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":195,
                      "y":363}},
                  "adaptiveStyles":{
},
                  "masterId":"cd8ed5398a604449bc3e5bd0e00b50ea"},
{
                  "id":"b81611b43c73440d9cb6b6e85b0a276e",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":820,
                      "y":363}},
                  "adaptiveStyles":{
},
                  "masterId":"cd8ed5398a604449bc3e5bd0e00b50ea"},
{
                  "id":"e3f011655669401b907075ae1c32f657",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":540,
                      "y":451},
                    "size":{
                      "width":100,
                      "height":19},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7c623cf672534d06bab9a434b399852a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":540,
                          "y":451},
                        "size":{
                          "width":100,
                          "height":19},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Bottow panel to SEQ ",
                              "panelsToStates":[{
                                  "panelPath":["b607696d51244291b0f39c58ed335861"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":4,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/judge_text/u56.png"}},
{
                  "id":"523df588e37942f397bdf44dc9ffcb1c",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":476,
                      "y":4},
                    "size":{
                      "width":196,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c759a31face24ff59e4d7184f7baa0e3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":476,
                          "y":4},
                        "size":{
                          "width":196,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "annotation":{
                    "Description":"&quot;Your feedback&quot; fields should only appear for certain papers of certain users. Backend should allow for flagging a user as requiring individual feedback."},
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"58b3e6e1749244ef9cd6feb4980c7ff4",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":685,
                      "y":11},
                    "size":{
                      "width":45,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dd1a840fbdb64250b0723aa5357269ce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":685,
                          "y":11},
                        "size":{
                          "width":45,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Bottow panel to Comparative fb and winner",
                              "panelsToStates":[{
                                  "panelPath":["b607696d51244291b0f39c58ed335861"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c235cd8077894be897ba1b1d4ea645a3",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":140,
                      "y":42},
                    "size":{
                      "width":228,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7d727f1324d64c1fadcf9a8f32a382fb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":140,
                          "y":42},
                        "size":{
                          "width":228,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"16b97b84f4154acba95efdaeefd5a8db",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":772,
                      "y":42},
                    "size":{
                      "width":217,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b252f633e7434013893e5edc1d70bc27",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":772,
                          "y":42},
                        "size":{
                          "width":217,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"2ae69359ce1d46dfa47cb6a7e5efd3eb",
              "label":"Z4 Unique feedback and pass/fail",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b76779d0532f483b8f0bee1a94bbae95",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":476,
                      "y":4},
                    "size":{
                      "width":182,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"23ef7be753164b2ca93db1f2dbffc13d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":476,
                          "y":4},
                        "size":{
                          "width":182,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "annotation":{
                    "Description":"&quot;Your feedback&quot; fields should only appear for certain papers of certain users. Backend should allow for flagging a user as requiring individual feedback."},
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"11048e8d3c1e4ac4bb91c63ab2d3155c",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":665,
                      "y":14},
                    "size":{
                      "width":45,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"565a2f3ea7fb47e195f750b8fb52dff5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":665,
                          "y":14},
                        "size":{
                          "width":45,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Bottow panel to Comparative fb and winner",
                              "panelsToStates":[{
                                  "panelPath":["b607696d51244291b0f39c58ed335861"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1e4d565a76a3458696a946bb5c7fd2af",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"textArea",
                  "styleType":"textArea",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":620,
                      "y":73},
                    "size":{
                      "width":560,
                      "height":261}},
                  "adaptiveStyles":{
}},
{
                  "id":"285ff79643fd415f929f88567340094d",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"textArea",
                  "styleType":"textArea",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":73},
                    "size":{
                      "width":560,
                      "height":261}},
                  "adaptiveStyles":{
}},
{
                  "id":"0e88294bd2964a968560dbb45fa5781a",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":195,
                      "y":363}},
                  "adaptiveStyles":{
},
                  "masterId":"cd8ed5398a604449bc3e5bd0e00b50ea"},
{
                  "id":"675fb125165543fbacc3f4c7840d738e",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":820,
                      "y":363}},
                  "adaptiveStyles":{
},
                  "masterId":"cd8ed5398a604449bc3e5bd0e00b50ea"},
{
                  "id":"fa8998b718d24e5c87133149291a6f18",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":540,
                      "y":451},
                    "size":{
                      "width":100,
                      "height":19},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"03b55f7589aa4a6eb904cdbb65f08d95",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":540,
                          "y":451},
                        "size":{
                          "width":100,
                          "height":19},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Bottow panel to SEQ ",
                              "panelsToStates":[{
                                  "panelPath":["b607696d51244291b0f39c58ed335861"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":4,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/judge_text/u56.png"}},
{
                  "id":"19722ad3ed70445d8ad1870f183d5d42",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":140,
                      "y":42},
                    "size":{
                      "width":228,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ca686430152e4b1191165e8ad1d0b5c8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":140,
                          "y":42},
                        "size":{
                          "width":228,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b9112a58cd214c53a3ae60c71f465610",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":772,
                      "y":42},
                    "size":{
                      "width":217,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f0b76e247a444d0fb6c22902d6d6795f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":772,
                          "y":42},
                        "size":{
                          "width":217,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"e116a227241d4c6383f3123e1c2d1d4f",
              "label":"SEQ ",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"aa3c0718e75f412e975aa5f5c93fd35c",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":540,
                      "y":230},
                    "size":{
                      "width":100,
                      "height":19},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f1a1df1244574ed49e9f153cafad1f77",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":540,
                          "y":230},
                        "size":{
                          "width":100,
                          "height":19},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Judge text in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"judge_text.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/judge_text/u56.png"}},
{
                  "id":"87e3f59ffc79466692030f5ffe337d2c",
                  "label":"",
                  "parentDynamicPanel":"b607696d51244291b0f39c58ed335861",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":270,
                      "y":50}},
                  "adaptiveStyles":{
},
                  "masterId":"794f25aebcda402d82e13af30930234a"}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "14818115d01f47f99a32087a167b2c37":{
      "packageId":"14818115d01f47f99a32087a167b2c37",
      "type":"Axure:Master",
      "name":"Assessor - Navigation logged in",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"21e93a6843644148a85b03371aa66f65",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":7},
              "size":{
                "width":120,
                "height":76}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"288080d3ea61437a8ab3dcd742a527a3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":7},
                  "size":{
                    "width":120,
                    "height":76}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/frontpage/u1.png"}},
{
            "id":"d7cce145214f41bfbc63f094a4be971f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":830,
                "y":30},
              "size":{
                "width":100,
                "height":30},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f42e483fc3c34f72a29f0d79f2b73812",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":830,
                    "y":30},
                  "size":{
                    "width":100,
                    "height":30},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Judge text in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"judge_text.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/frontpage/u3.png"}},
{
            "id":"1c05e89a69dc42fabb5624cf6fe99da3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":960,
                "y":30},
              "size":{
                "width":100,
                "height":30},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"58b355072b67418aa9d36e56eb847646",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":960,
                    "y":30},
                  "size":{
                    "width":100,
                    "height":30},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Account in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"account.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/frontpage/u3.png"}},
{
            "id":"5a869bed0e234a1a9a2fd89d3d07abc5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":1090,
                "y":30},
              "size":{
                "width":100,
                "height":30},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59bde9dac5084b7ca662286523ad3b20",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1090,
                    "y":30},
                  "size":{
                    "width":100,
                    "height":30},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Frontpage in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"frontpage.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/frontpage/u3.png"}}]}},
    "cd8ed5398a604449bc3e5bd0e00b50ea":{
      "packageId":"cd8ed5398a604449bc3e5bd0e00b50ea",
      "type":"Axure:Master",
      "name":"Assessor - succeed/fail widget",
      "notes":{
        "Default":"<p><span>Check on submit if not blanc</span></p>"},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"b5506ea8a5cc4f2a8dc968f89a106fd8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "horizontalAlignment":"left",
              "verticalAlignment":"top",
              "location":{
                "x":10,
                "y":0},
              "size":{
                "width":180,
                "height":100},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"30e6787de25f44dea73ba6fe1bd50c0c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"left",
                  "verticalAlignment":"top",
                  "location":{
                    "x":10,
                    "y":0},
                  "size":{
                    "width":180,
                    "height":100},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/judge_text/u39.png",
              "normal~":"images/judge_text/u39.png",
              "normal~":"images/judge_text/u39.png",
              "normal~":"images/judge_text/u39.png"}},
{
            "id":"a44e5786f65d47e18706ddcc9b34ef1c",
            "label":"",
            "type":"radioButton",
            "styleType":"radioButton",
            "visible":true,
            "style":{
              "location":{
                "x":70,
                "y":25},
              "size":{
                "width":100,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b62e39f2154a46e59f8300fc81d47dd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":70,
                    "y":25},
                  "size":{
                    "width":100,
                    "height":15}},
                "adaptiveStyles":{
}}]},
{
            "id":"2f4622d1335a4523aa6c3020b28c84e9",
            "label":"",
            "type":"radioButton",
            "styleType":"radioButton",
            "visible":true,
            "style":{
              "location":{
                "x":70,
                "y":50},
              "size":{
                "width":100,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"158eadccc266435bbc662f553c6b3c47",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":70,
                    "y":50},
                  "size":{
                    "width":100,
                    "height":15}},
                "adaptiveStyles":{
}}]},
{
            "id":"3b6242d3da9a4a9693b23080d3f87cc6",
            "label":"",
            "type":"radioButton",
            "styleType":"radioButton",
            "visible":true,
            "style":{
              "location":{
                "x":70,
                "y":75},
              "size":{
                "width":100,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4ca62baf7aa2418f8e4203672cf661b7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":70,
                    "y":75},
                  "size":{
                    "width":100,
                    "height":15}},
                "adaptiveStyles":{
}}]}]}},
    "794f25aebcda402d82e13af30930234a":{
      "packageId":"794f25aebcda402d82e13af30930234a",
      "type":"Axure:Master",
      "name":"Assessor - SEQ scale",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"6cdbb2e225ff4f70882b45f4e58c9202",
            "label":"",
            "type":"radioButton",
            "styleType":"radioButton",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"bottom",
              "location":{
                "x":441,
                "y":94},
              "size":{
                "width":127,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e0e2377d238a4f14898621edfd7aaa4e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"bottom",
                  "location":{
                    "x":441,
                    "y":94},
                  "size":{
                    "width":127,
                    "height":16}},
                "adaptiveStyles":{
}}]},
{
            "id":"3d4e1b81f7cc4ebc8a5eca404f2bbea8",
            "label":"",
            "type":"radioButton",
            "styleType":"radioButton",
            "visible":true,
            "style":{
              "horizontalAlignment":"right",
              "verticalAlignment":"bottom",
              "location":{
                "x":-50,
                "y":94},
              "size":{
                "width":137,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"93853d1762cd4216ad8687882188dcac",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"right",
                  "verticalAlignment":"bottom",
                  "location":{
                    "x":-50,
                    "y":94},
                  "size":{
                    "width":137,
                    "height":16}},
                "adaptiveStyles":{
}}]},
{
            "id":"705cd9ed11644043bbf27a3e9476a1d8",
            "label":"",
            "type":"radioButton",
            "styleType":"radioButton",
            "visible":true,
            "style":{
              "horizontalAlignment":"right",
              "verticalAlignment":"bottom",
              "location":{
                "x":30,
                "y":94},
              "size":{
                "width":137,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"996a001219264c1fb94120deac84e696",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"right",
                  "verticalAlignment":"bottom",
                  "location":{
                    "x":30,
                    "y":94},
                  "size":{
                    "width":137,
                    "height":16}},
                "adaptiveStyles":{
}}]},
{
            "id":"626bac1503b14663b874b6e1d61cfa2d",
            "label":"",
            "type":"radioButton",
            "styleType":"radioButton",
            "visible":true,
            "style":{
              "horizontalAlignment":"right",
              "verticalAlignment":"bottom",
              "location":{
                "x":230,
                "y":94},
              "size":{
                "width":17,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1ed419668b2e45c4bd8133313f27732a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"right",
                  "verticalAlignment":"bottom",
                  "location":{
                    "x":230,
                    "y":94},
                  "size":{
                    "width":17,
                    "height":16}},
                "adaptiveStyles":{
}}]},
{
            "id":"8e516d8da1f24369b7e5301deb2f3799",
            "label":"",
            "type":"radioButton",
            "styleType":"radioButton",
            "visible":true,
            "style":{
              "horizontalAlignment":"right",
              "verticalAlignment":"bottom",
              "location":{
                "x":310,
                "y":94},
              "size":{
                "width":17,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ebec0d1ee4164b02aceb53506966f16f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"right",
                  "verticalAlignment":"bottom",
                  "location":{
                    "x":310,
                    "y":94},
                  "size":{
                    "width":17,
                    "height":16}},
                "adaptiveStyles":{
}}]},
{
            "id":"a78eb9bb07d34aa5864aa3349ad58b20",
            "label":"",
            "type":"radioButton",
            "styleType":"radioButton",
            "visible":true,
            "style":{
              "horizontalAlignment":"right",
              "verticalAlignment":"bottom",
              "location":{
                "x":393,
                "y":94},
              "size":{
                "width":17,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b967da76751a45278ae3c4d004b1dd5c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"right",
                  "verticalAlignment":"bottom",
                  "location":{
                    "x":393,
                    "y":94},
                  "size":{
                    "width":17,
                    "height":16}},
                "adaptiveStyles":{
}}]},
{
            "id":"007ffa7ad49447f6bcfaaa2cd0328f9b",
            "label":"",
            "type":"radioButton",
            "styleType":"radioButton",
            "visible":true,
            "style":{
              "horizontalAlignment":"right",
              "verticalAlignment":"bottom",
              "location":{
                "x":471,
                "y":94},
              "size":{
                "width":17,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c45c38b8c56d4324afdec1502269b79a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"right",
                  "verticalAlignment":"bottom",
                  "location":{
                    "x":471,
                    "y":94},
                  "size":{
                    "width":17,
                    "height":16}},
                "adaptiveStyles":{
}}]},
{
            "id":"22af351f02ab46209456c2749eb44716",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":49},
              "size":{
                "width":80,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d5dba630c7324f6a846a78d95e6427e2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":49},
                  "size":{
                    "width":80,
                    "height":15}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"fc73fec9bb9d46c187ec02264c7330ef",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":529,
                "y":49},
              "size":{
                "width":61,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c6f347de4e56430c9299b0ec22748e6e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":529,
                    "y":49},
                  "size":{
                    "width":61,
                    "height":15}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8d9b96ef36b1491195016efdf515304b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":76,
                "y":69},
              "size":{
                "width":11,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"956f225c3f3048459a6224ccda8f646f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":76,
                    "y":69},
                  "size":{
                    "width":11,
                    "height":15}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3b431c5cd65a4d2db24fcb994df58d59",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":557,
                "y":69},
              "size":{
                "width":24,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3bfaa847a8c04415905ff98fb8f03296",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":557,
                    "y":69},
                  "size":{
                    "width":24,
                    "height":15}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"cd61a9ca57424a888f138586c572c631",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":157,
                "y":69},
              "size":{
                "width":11,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"daed0842a725445cb04fe139cd042936",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":157,
                    "y":69},
                  "size":{
                    "width":11,
                    "height":15}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c063edb1be714471994334ebac09c8dd",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":236,
                "y":69},
              "size":{
                "width":11,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"36e0b865441e498fbe53fb27065c7e1e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":236,
                    "y":69},
                  "size":{
                    "width":11,
                    "height":15}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c77594c1aa94464dad9b86efac27c845",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":316,
                "y":69},
              "size":{
                "width":11,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d0135f220cca43759d7e5d27fb1c8d8f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":316,
                    "y":69},
                  "size":{
                    "width":11,
                    "height":15}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"84b1db35334a44faa9586f5c2b127d26",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":397,
                "y":69},
              "size":{
                "width":11,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0cb58c79f1ac40c6a15d555acfec095a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":397,
                    "y":69},
                  "size":{
                    "width":11,
                    "height":15}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a574d6643d884ce2a1a460c095d14de1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":477,
                "y":69},
              "size":{
                "width":11,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8bf820f0679544ddaa05aea5fa9be09f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":477,
                    "y":69},
                  "size":{
                    "width":11,
                    "height":15}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"59aa20250e1748648d47bb1b98ee5728",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Bold', 'Arial'",
              "fontSize":"24px",
              "fontWeight":"700",
              "location":{
                "x":92,
                "y":11},
              "size":{
                "width":508,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24b11427eac243ebbe12a9777fb6edd3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Bold', 'Arial'",
                  "fontSize":"24px",
                  "fontWeight":"700",
                  "location":{
                    "x":92,
                    "y":11},
                  "size":{
                    "width":508,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "annotation":{
              "Description":"This widget should appear at random after each hit of the submit button according to a certain rule. For example, the appearance of the panel could be done according to a certain probability (e.g. 1/10)"},
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "66e34840702941d0b6c6e5b75386019a":{
      "scriptId":"u0"},
    "e3d3455028a94212aeb12b937f044eb5":{
      "scriptId":"u1"},
    "90049410b8754ac1aee46f739746dacd":{
      "scriptId":"u2"},
    "e34ed8bbeddb48d0ab956f5bddda07a0":{
      "scriptId":"u3",
      "21e93a6843644148a85b03371aa66f65":{
        "scriptId":"u4"},
      "288080d3ea61437a8ab3dcd742a527a3":{
        "scriptId":"u5"},
      "d7cce145214f41bfbc63f094a4be971f":{
        "scriptId":"u6"},
      "f42e483fc3c34f72a29f0d79f2b73812":{
        "scriptId":"u7"},
      "1c05e89a69dc42fabb5624cf6fe99da3":{
        "scriptId":"u8"},
      "58b355072b67418aa9d36e56eb847646":{
        "scriptId":"u9"},
      "5a869bed0e234a1a9a2fd89d3d07abc5":{
        "scriptId":"u10"},
      "59bde9dac5084b7ca662286523ad3b20":{
        "scriptId":"u11"}},
    "948e94c1fe164040bfe13a0707d4796a":{
      "scriptId":"u12"},
    "c69d61749d5a4cc9907740bb19baeb8a":{
      "scriptId":"u13"},
    "ac21e6701d144b6d81a0d38ffec35db2":{
      "scriptId":"u14"},
    "b93a925d53f04dc7b163516ede556cea":{
      "scriptId":"u15"},
    "5255a26171ab4ff39e6202ff74b3f239":{
      "scriptId":"u16"},
    "d0dd2460f63844baafd6dc0b5e68e3d2":{
      "scriptId":"u17"},
    "a1bf9149b35f451183faf122ed0dfc9f":{
      "scriptId":"u18"},
    "7e35bc25679b4256b7e4cc010bf2517f":{
      "scriptId":"u19"},
    "7b9aafee082c404b813b66ba4479eaa6":{
      "scriptId":"u20"},
    "eba95009beac42dcae540d5ab8c87d69":{
      "scriptId":"u21"},
    "d4dddbc9265f4764aef8d76a8bd32055":{
      "scriptId":"u22"},
    "0883b941f70b4df1bc5a3e73de531da6":{
      "scriptId":"u23"},
    "4cf88d0b30f946d4bd88c0151d599d57":{
      "scriptId":"u24"},
    "e3915b4763724c1f8666928c93651ded":{
      "scriptId":"u25"},
    "cb0b9f7296d94ca78e7ab27a9cba380e":{
      "scriptId":"u26"},
    "41b164983be84fc4846aedc0f73981c2":{
      "scriptId":"u27"},
    "b607696d51244291b0f39c58ed335861":{
      "scriptId":"u28"},
    "0e4ccd11698b4761b616f903a1cdc9a8":{
      "scriptId":"u29"},
    "2356e11b34fa4d68abfe6782e6cbc4a2":{
      "scriptId":"u30"},
    "d6e63e75dc1a4e85a7ebe2007c543331":{
      "scriptId":"u31"},
    "ca750648c46348c5a5694921251589a4":{
      "scriptId":"u32"},
    "3de380b8f0a04f3e92fa68ea3ae3fcd3":{
      "scriptId":"u33"},
    "5d743a04e4ef4ad9925803574a1bf77c":{
      "scriptId":"u34"},
    "6a4eed4b02ec4c498aebf4f4a36cb250":{
      "scriptId":"u35"},
    "58ab3fc4241642ad9aa6ea490d01102d":{
      "scriptId":"u36"},
    "0ee5702d438642c988d8b36d5b5ae8cf":{
      "scriptId":"u37"},
    "ece8781e26ec4ecc8300d253ba5a6823":{
      "scriptId":"u38",
      "b5506ea8a5cc4f2a8dc968f89a106fd8":{
        "scriptId":"u39"},
      "30e6787de25f44dea73ba6fe1bd50c0c":{
        "scriptId":"u40"},
      "a44e5786f65d47e18706ddcc9b34ef1c":{
        "scriptId":"u41"},
      "b62e39f2154a46e59f8300fc81d47dd8":{
        "scriptId":"u42"},
      "2f4622d1335a4523aa6c3020b28c84e9":{
        "scriptId":"u43"},
      "158eadccc266435bbc662f553c6b3c47":{
        "scriptId":"u44"},
      "3b6242d3da9a4a9693b23080d3f87cc6":{
        "scriptId":"u45"},
      "4ca62baf7aa2418f8e4203672cf661b7":{
        "scriptId":"u46"}},
    "b81611b43c73440d9cb6b6e85b0a276e":{
      "scriptId":"u47",
      "b5506ea8a5cc4f2a8dc968f89a106fd8":{
        "scriptId":"u48"},
      "30e6787de25f44dea73ba6fe1bd50c0c":{
        "scriptId":"u49"},
      "a44e5786f65d47e18706ddcc9b34ef1c":{
        "scriptId":"u50"},
      "b62e39f2154a46e59f8300fc81d47dd8":{
        "scriptId":"u51"},
      "2f4622d1335a4523aa6c3020b28c84e9":{
        "scriptId":"u52"},
      "158eadccc266435bbc662f553c6b3c47":{
        "scriptId":"u53"},
      "3b6242d3da9a4a9693b23080d3f87cc6":{
        "scriptId":"u54"},
      "4ca62baf7aa2418f8e4203672cf661b7":{
        "scriptId":"u55"}},
    "e3f011655669401b907075ae1c32f657":{
      "scriptId":"u56"},
    "7c623cf672534d06bab9a434b399852a":{
      "scriptId":"u57"},
    "523df588e37942f397bdf44dc9ffcb1c":{
      "scriptId":"u58"},
    "c759a31face24ff59e4d7184f7baa0e3":{
      "scriptId":"u59"},
    "58b3e6e1749244ef9cd6feb4980c7ff4":{
      "scriptId":"u60"},
    "dd1a840fbdb64250b0723aa5357269ce":{
      "scriptId":"u61"},
    "c235cd8077894be897ba1b1d4ea645a3":{
      "scriptId":"u62"},
    "7d727f1324d64c1fadcf9a8f32a382fb":{
      "scriptId":"u63"},
    "16b97b84f4154acba95efdaeefd5a8db":{
      "scriptId":"u64"},
    "b252f633e7434013893e5edc1d70bc27":{
      "scriptId":"u65"},
    "b76779d0532f483b8f0bee1a94bbae95":{
      "scriptId":"u66"},
    "23ef7be753164b2ca93db1f2dbffc13d":{
      "scriptId":"u67"},
    "11048e8d3c1e4ac4bb91c63ab2d3155c":{
      "scriptId":"u68"},
    "565a2f3ea7fb47e195f750b8fb52dff5":{
      "scriptId":"u69"},
    "1e4d565a76a3458696a946bb5c7fd2af":{
      "scriptId":"u70"},
    "285ff79643fd415f929f88567340094d":{
      "scriptId":"u71"},
    "0e88294bd2964a968560dbb45fa5781a":{
      "scriptId":"u72",
      "b5506ea8a5cc4f2a8dc968f89a106fd8":{
        "scriptId":"u73"},
      "30e6787de25f44dea73ba6fe1bd50c0c":{
        "scriptId":"u74"},
      "a44e5786f65d47e18706ddcc9b34ef1c":{
        "scriptId":"u75"},
      "b62e39f2154a46e59f8300fc81d47dd8":{
        "scriptId":"u76"},
      "2f4622d1335a4523aa6c3020b28c84e9":{
        "scriptId":"u77"},
      "158eadccc266435bbc662f553c6b3c47":{
        "scriptId":"u78"},
      "3b6242d3da9a4a9693b23080d3f87cc6":{
        "scriptId":"u79"},
      "4ca62baf7aa2418f8e4203672cf661b7":{
        "scriptId":"u80"}},
    "675fb125165543fbacc3f4c7840d738e":{
      "scriptId":"u81",
      "b5506ea8a5cc4f2a8dc968f89a106fd8":{
        "scriptId":"u82"},
      "30e6787de25f44dea73ba6fe1bd50c0c":{
        "scriptId":"u83"},
      "a44e5786f65d47e18706ddcc9b34ef1c":{
        "scriptId":"u84"},
      "b62e39f2154a46e59f8300fc81d47dd8":{
        "scriptId":"u85"},
      "2f4622d1335a4523aa6c3020b28c84e9":{
        "scriptId":"u86"},
      "158eadccc266435bbc662f553c6b3c47":{
        "scriptId":"u87"},
      "3b6242d3da9a4a9693b23080d3f87cc6":{
        "scriptId":"u88"},
      "4ca62baf7aa2418f8e4203672cf661b7":{
        "scriptId":"u89"}},
    "fa8998b718d24e5c87133149291a6f18":{
      "scriptId":"u90"},
    "03b55f7589aa4a6eb904cdbb65f08d95":{
      "scriptId":"u91"},
    "19722ad3ed70445d8ad1870f183d5d42":{
      "scriptId":"u92"},
    "ca686430152e4b1191165e8ad1d0b5c8":{
      "scriptId":"u93"},
    "b9112a58cd214c53a3ae60c71f465610":{
      "scriptId":"u94"},
    "f0b76e247a444d0fb6c22902d6d6795f":{
      "scriptId":"u95"},
    "aa3c0718e75f412e975aa5f5c93fd35c":{
      "scriptId":"u96"},
    "f1a1df1244574ed49e9f153cafad1f77":{
      "scriptId":"u97"},
    "87e3f59ffc79466692030f5ffe337d2c":{
      "scriptId":"u98",
      "6cdbb2e225ff4f70882b45f4e58c9202":{
        "scriptId":"u99"},
      "e0e2377d238a4f14898621edfd7aaa4e":{
        "scriptId":"u100"},
      "3d4e1b81f7cc4ebc8a5eca404f2bbea8":{
        "scriptId":"u101"},
      "93853d1762cd4216ad8687882188dcac":{
        "scriptId":"u102"},
      "705cd9ed11644043bbf27a3e9476a1d8":{
        "scriptId":"u103"},
      "996a001219264c1fb94120deac84e696":{
        "scriptId":"u104"},
      "626bac1503b14663b874b6e1d61cfa2d":{
        "scriptId":"u105"},
      "1ed419668b2e45c4bd8133313f27732a":{
        "scriptId":"u106"},
      "8e516d8da1f24369b7e5301deb2f3799":{
        "scriptId":"u107"},
      "ebec0d1ee4164b02aceb53506966f16f":{
        "scriptId":"u108"},
      "a78eb9bb07d34aa5864aa3349ad58b20":{
        "scriptId":"u109"},
      "b967da76751a45278ae3c4d004b1dd5c":{
        "scriptId":"u110"},
      "007ffa7ad49447f6bcfaaa2cd0328f9b":{
        "scriptId":"u111"},
      "c45c38b8c56d4324afdec1502269b79a":{
        "scriptId":"u112"},
      "22af351f02ab46209456c2749eb44716":{
        "scriptId":"u113"},
      "d5dba630c7324f6a846a78d95e6427e2":{
        "scriptId":"u114"},
      "fc73fec9bb9d46c187ec02264c7330ef":{
        "scriptId":"u115"},
      "c6f347de4e56430c9299b0ec22748e6e":{
        "scriptId":"u116"},
      "8d9b96ef36b1491195016efdf515304b":{
        "scriptId":"u117"},
      "956f225c3f3048459a6224ccda8f646f":{
        "scriptId":"u118"},
      "3b431c5cd65a4d2db24fcb994df58d59":{
        "scriptId":"u119"},
      "3bfaa847a8c04415905ff98fb8f03296":{
        "scriptId":"u120"},
      "cd61a9ca57424a888f138586c572c631":{
        "scriptId":"u121"},
      "daed0842a725445cb04fe139cd042936":{
        "scriptId":"u122"},
      "c063edb1be714471994334ebac09c8dd":{
        "scriptId":"u123"},
      "36e0b865441e498fbe53fb27065c7e1e":{
        "scriptId":"u124"},
      "c77594c1aa94464dad9b86efac27c845":{
        "scriptId":"u125"},
      "d0135f220cca43759d7e5d27fb1c8d8f":{
        "scriptId":"u126"},
      "84b1db35334a44faa9586f5c2b127d26":{
        "scriptId":"u127"},
      "0cb58c79f1ac40c6a15d555acfec095a":{
        "scriptId":"u128"},
      "a574d6643d884ce2a1a460c095d14de1":{
        "scriptId":"u129"},
      "8bf820f0679544ddaa05aea5fa9be09f":{
        "scriptId":"u130"},
      "59aa20250e1748648d47bb1b98ee5728":{
        "scriptId":"u131"},
      "24b11427eac243ebbe12a9777fb6edd3":{
        "scriptId":"u132"}}}});