$axure.loadCurrentPage({
  "url":"judge_video.html",
  "generationDate":new Date(1396428149096.19),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ae7b14d013254304bc363c9a5dad1a67",
    "type":"Axure:Page",
    "name":"Judge video",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setWidgetSize",
                "description":"Set Size of winner confirmation popup to 0 x 0",
                "objectsToResize":[{
                    "objectPath":["467b03a2529348a7a49b7ecf8fe336df"],
                    "sizeInfo":{
                      "width":{
                        "exprType":"stringLiteral",
                        "value":"0",
                        "stos":[]},
                      "height":{
                        "exprType":"stringLiteral",
                        "value":"0",
                        "stos":[]},
                      "easing":"none",
                      "duration":1000}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"3392d7dc7ee441779e5f3cd887c6ba6b",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":431},
            "size":{
              "width":560,
              "height":370}},
          "adaptiveStyles":{
}},
{
          "id":"d7e15fc6b2304dc299f09e8159941587",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":431},
            "size":{
              "width":560,
              "height":370}},
          "adaptiveStyles":{
}},
{
          "id":"66e34840702941d0b6c6e5b75386019a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":446,
              "y":110},
            "size":{
              "width":307,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3d3455028a94212aeb12b937f044eb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":446,
                  "y":110},
                "size":{
                  "width":307,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90049410b8754ac1aee46f739746dacd",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":190},
            "size":{
              "width":1180,
              "height":150}},
          "adaptiveStyles":{
}},
{
          "id":"e34ed8bbeddb48d0ab956f5bddda07a0",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"14818115d01f47f99a32087a167b2c37"},
{
          "id":"d990ec6f7ce14ce3b5a0df19b7764813",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":824},
            "size":{
              "width":560,
              "height":200}},
          "adaptiveStyles":{
}},
{
          "id":"df1c339efbe544a2b3dcf40d7391f10b",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":824},
            "size":{
              "width":560,
              "height":200}},
          "adaptiveStyles":{
}},
{
          "id":"7531380fa1ea40c09fa198bbb2ea1421",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":382},
            "size":{
              "width":89,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dc8c7aaf04e4443b5cd84746a6676a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":382},
                "size":{
                  "width":89,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aaf4bba2ad5044af836ef5457b9ed314",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":382},
            "size":{
              "width":90,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02a967d00bc946c8b904161ea7b6134d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":870,
                  "y":382},
                "size":{
                  "width":90,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"467b03a2529348a7a49b7ecf8fe336df",
          "label":"winner confirmation popup",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":10},
            "size":{
              "width":1086,
              "height":1120}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"4827071e13534095a0f25ad42c9bf152",
              "label":"video A won",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"87b76a48676d40f9a27de7bcb9f3521d",
                  "label":"",
                  "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "masterId":"f4885c44fb0d46de8c5935239991d560"},
{
                  "id":"6b6e6a3de4aa4c748a87ba14230cebe3",
                  "label":"",
                  "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":319,
                      "y":120},
                    "size":{
                      "width":445,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b80416f60d8e4441bfcdfffaa3927e6e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":319,
                          "y":120},
                        "size":{
                          "width":445,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"de95c5e188bc4f779d829f5396d37918",
                  "label":"",
                  "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":664,
                      "y":277.5},
                    "size":{
                      "width":100,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"168aed17dd7147c99c40426d5558a132",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":664,
                          "y":277.5},
                        "size":{
                          "width":100,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Judge video in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"judge_video.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/frontpage/u3.png"}},
{
                  "id":"ada44610b1c44d9598bf06772c7d9035",
                  "label":"",
                  "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":319,
                      "y":278},
                    "size":{
                      "width":100,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0bad558ad97d4b92a1d8475f0e61bfd6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":319,
                          "y":278},
                        "size":{
                          "width":100,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Judge video in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"judge_video.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/frontpage/u3.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"26e40f1c5ddb4ed5a4bddf60d45b9504",
              "label":"video B won",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"85d02ec997f149758e3c2bff8ddfcdaf",
                  "label":"",
                  "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "masterId":"f4885c44fb0d46de8c5935239991d560"},
{
                  "id":"4dbc1ece58334ac88ce6df03783b8e41",
                  "label":"",
                  "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":319,
                      "y":120},
                    "size":{
                      "width":448,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"884ff7173efd4dedafbb8d406b47c78c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":319,
                          "y":120},
                        "size":{
                          "width":448,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"54318fff7adf432584d8216f783371bd",
                  "label":"",
                  "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":664,
                      "y":277.5},
                    "size":{
                      "width":100,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4564e15f40ee41749ea056fbe984b4b2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":664,
                          "y":277.5},
                        "size":{
                          "width":100,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Judge video in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"judge_video.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/frontpage/u3.png"}},
{
                  "id":"dfdb8b942b164d3188171e7b0e112603",
                  "label":"",
                  "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":319,
                      "y":278},
                    "size":{
                      "width":100,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"11f316e9a4fe4470bb06354fcd5fec34",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"467b03a2529348a7a49b7ecf8fe336df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":319,
                          "y":278},
                        "size":{
                          "width":100,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Judge video in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"judge_video.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/frontpage/u3.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"d5a556938a904ab0a841522593f6058a",
          "label":"winner A button",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":1080},
            "size":{
              "width":140,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9aee76e71fc14b3283b2b81ae2c825aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":1080},
                "size":{
                  "width":140,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setWidgetSize",
                      "description":"Set Size of winner confirmation popup to 1086 x 1120",
                      "objectsToResize":[{
                          "objectPath":["467b03a2529348a7a49b7ecf8fe336df"],
                          "sizeInfo":{
                            "width":{
                              "exprType":"stringLiteral",
                              "value":"1086",
                              "stos":[]},
                            "height":{
                              "exprType":"stringLiteral",
                              "value":"1120",
                              "stos":[]},
                            "easing":"none",
                            "duration":1000}}]},
{
                      "action":"setPanelState",
                      "description":"Set winner confirmation popup to video A won",
                      "panelsToStates":[{
                          "panelPath":["467b03a2529348a7a49b7ecf8fe336df"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/judge_text/winner_a_button_u39.png"}},
{
          "id":"dfee7405918a4f429a125cf259fcec2f",
          "label":"winner B button",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":860,
              "y":1080},
            "size":{
              "width":140,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ba553bec5ab4fef8a56e3be0a6f9392",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":860,
                  "y":1080},
                "size":{
                  "width":140,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setWidgetSize",
                      "description":"Set Size of winner confirmation popup to 1086 x 1120",
                      "objectsToResize":[{
                          "objectPath":["467b03a2529348a7a49b7ecf8fe336df"],
                          "sizeInfo":{
                            "width":{
                              "exprType":"stringLiteral",
                              "value":"1086",
                              "stos":[]},
                            "height":{
                              "exprType":"stringLiteral",
                              "value":"1120",
                              "stos":[]},
                            "easing":"none",
                            "duration":1000}}]},
{
                      "action":"setPanelState",
                      "description":"Set winner confirmation popup to video B won",
                      "panelsToStates":[{
                          "panelPath":["467b03a2529348a7a49b7ecf8fe336df"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/judge_text/winner_a_button_u39.png"}},
{
          "id":"948e94c1fe164040bfe13a0707d4796a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":0,
              "y":1190},
            "size":{
              "width":1500,
              "height":100},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c69d61749d5a4cc9907740bb19baeb8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":0,
                  "y":1190},
                "size":{
                  "width":1500,
                  "height":100},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/judge_video/u47.png"}}]}},
  "masters":{
    "14818115d01f47f99a32087a167b2c37":{
      "packageId":"14818115d01f47f99a32087a167b2c37",
      "type":"Axure:Master",
      "name":"Assessor - Navigation logged in",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"21e93a6843644148a85b03371aa66f65",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":7},
              "size":{
                "width":120,
                "height":76}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"288080d3ea61437a8ab3dcd742a527a3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":7},
                  "size":{
                    "width":120,
                    "height":76}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/frontpage/u1.png"}},
{
            "id":"d7cce145214f41bfbc63f094a4be971f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":830,
                "y":30},
              "size":{
                "width":100,
                "height":30},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f42e483fc3c34f72a29f0d79f2b73812",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":830,
                    "y":30},
                  "size":{
                    "width":100,
                    "height":30},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Judge text in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"judge_text.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/frontpage/u3.png"}},
{
            "id":"1c05e89a69dc42fabb5624cf6fe99da3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":960,
                "y":30},
              "size":{
                "width":100,
                "height":30},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"58b355072b67418aa9d36e56eb847646",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":960,
                    "y":30},
                  "size":{
                    "width":100,
                    "height":30},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Account in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"account.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/frontpage/u3.png"}},
{
            "id":"5a869bed0e234a1a9a2fd89d3d07abc5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":1090,
                "y":30},
              "size":{
                "width":100,
                "height":30},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59bde9dac5084b7ca662286523ad3b20",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1090,
                    "y":30},
                  "size":{
                    "width":100,
                    "height":30},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Frontpage in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"frontpage.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/frontpage/u3.png"}}]}},
    "f4885c44fb0d46de8c5935239991d560":{
      "packageId":"f4885c44fb0d46de8c5935239991d560",
      "type":"Axure:Master",
      "name":"Asessor - Judgement popup background",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f2ef4542332e41989a2c360a86a6df2b",
            "label":"Rectangle",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "opacity":"0.8",
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":-350,
                "y":-270},
              "size":{
                "width":1550,
                "height":1570},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF999999}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3be3eb3150a54a60a65d70d38981a7bf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "opacity":"0.8",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":-350,
                    "y":-270},
                  "size":{
                    "width":1550,
                    "height":1570},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF999999}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/judge_text/rectangle_u18.png",
              "normal~":"images/judge_text/rectangle_u18.png"}},
{
            "id":"81ea4546eed64b6abfea7f86e5337273",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "opacity":"0.8",
              "fill":{
                "fillType":"solid",
                "color":0xFF0099FF},
              "location":{
                "x":230,
                "y":50},
              "size":{
                "width":740,
                "height":340},
              "cornerRadiusTopLeft":"10"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a1133b112281405885f764ba66ccc361",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "opacity":"0.8",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF},
                  "location":{
                    "x":230,
                    "y":50},
                  "size":{
                    "width":740,
                    "height":340},
                  "cornerRadiusTopLeft":"10"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/judge_text/u20.png",
              "normal~":"images/judge_text/u20.png"}}]}}},
  "objectPaths":{
    "3392d7dc7ee441779e5f3cd887c6ba6b":{
      "scriptId":"u0"},
    "d7e15fc6b2304dc299f09e8159941587":{
      "scriptId":"u1"},
    "66e34840702941d0b6c6e5b75386019a":{
      "scriptId":"u2"},
    "e3d3455028a94212aeb12b937f044eb5":{
      "scriptId":"u3"},
    "90049410b8754ac1aee46f739746dacd":{
      "scriptId":"u4"},
    "e34ed8bbeddb48d0ab956f5bddda07a0":{
      "scriptId":"u5",
      "21e93a6843644148a85b03371aa66f65":{
        "scriptId":"u6"},
      "288080d3ea61437a8ab3dcd742a527a3":{
        "scriptId":"u7"},
      "d7cce145214f41bfbc63f094a4be971f":{
        "scriptId":"u8"},
      "f42e483fc3c34f72a29f0d79f2b73812":{
        "scriptId":"u9"},
      "1c05e89a69dc42fabb5624cf6fe99da3":{
        "scriptId":"u10"},
      "58b355072b67418aa9d36e56eb847646":{
        "scriptId":"u11"},
      "5a869bed0e234a1a9a2fd89d3d07abc5":{
        "scriptId":"u12"},
      "59bde9dac5084b7ca662286523ad3b20":{
        "scriptId":"u13"}},
    "d990ec6f7ce14ce3b5a0df19b7764813":{
      "scriptId":"u14"},
    "df1c339efbe544a2b3dcf40d7391f10b":{
      "scriptId":"u15"},
    "7531380fa1ea40c09fa198bbb2ea1421":{
      "scriptId":"u16"},
    "4dc8c7aaf04e4443b5cd84746a6676a9":{
      "scriptId":"u17"},
    "aaf4bba2ad5044af836ef5457b9ed314":{
      "scriptId":"u18"},
    "02a967d00bc946c8b904161ea7b6134d":{
      "scriptId":"u19"},
    "467b03a2529348a7a49b7ecf8fe336df":{
      "scriptId":"u20"},
    "87b76a48676d40f9a27de7bcb9f3521d":{
      "scriptId":"u21",
      "f2ef4542332e41989a2c360a86a6df2b":{
        "scriptId":"u22"},
      "3be3eb3150a54a60a65d70d38981a7bf":{
        "scriptId":"u23"},
      "81ea4546eed64b6abfea7f86e5337273":{
        "scriptId":"u24"},
      "a1133b112281405885f764ba66ccc361":{
        "scriptId":"u25"}},
    "6b6e6a3de4aa4c748a87ba14230cebe3":{
      "scriptId":"u26"},
    "b80416f60d8e4441bfcdfffaa3927e6e":{
      "scriptId":"u27"},
    "de95c5e188bc4f779d829f5396d37918":{
      "scriptId":"u28"},
    "168aed17dd7147c99c40426d5558a132":{
      "scriptId":"u29"},
    "ada44610b1c44d9598bf06772c7d9035":{
      "scriptId":"u30"},
    "0bad558ad97d4b92a1d8475f0e61bfd6":{
      "scriptId":"u31"},
    "85d02ec997f149758e3c2bff8ddfcdaf":{
      "scriptId":"u32",
      "f2ef4542332e41989a2c360a86a6df2b":{
        "scriptId":"u33"},
      "3be3eb3150a54a60a65d70d38981a7bf":{
        "scriptId":"u34"},
      "81ea4546eed64b6abfea7f86e5337273":{
        "scriptId":"u35"},
      "a1133b112281405885f764ba66ccc361":{
        "scriptId":"u36"}},
    "4dbc1ece58334ac88ce6df03783b8e41":{
      "scriptId":"u37"},
    "884ff7173efd4dedafbb8d406b47c78c":{
      "scriptId":"u38"},
    "54318fff7adf432584d8216f783371bd":{
      "scriptId":"u39"},
    "4564e15f40ee41749ea056fbe984b4b2":{
      "scriptId":"u40"},
    "dfdb8b942b164d3188171e7b0e112603":{
      "scriptId":"u41"},
    "11f316e9a4fe4470bb06354fcd5fec34":{
      "scriptId":"u42"},
    "d5a556938a904ab0a841522593f6058a":{
      "scriptId":"u43"},
    "9aee76e71fc14b3283b2b81ae2c825aa":{
      "scriptId":"u44"},
    "dfee7405918a4f429a125cf259fcec2f":{
      "scriptId":"u45"},
    "9ba553bec5ab4fef8a56e3be0a6f9392":{
      "scriptId":"u46"},
    "948e94c1fe164040bfe13a0707d4796a":{
      "scriptId":"u47"},
    "c69d61749d5a4cc9907740bb19baeb8a":{
      "scriptId":"u48"}}});